sources:
  - name: ownership
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sbauch/nfight-ownership
      batch: true
    transforms:
      - typeMerging:
          queryFields:
            # With batching
            - queryFieldName: fighters
              keyField: id
              keyArg: 'where.id_in'

  - name: savestate
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sbauch/nfight-gamedata
      batch: false
    transforms:
    #     - prefix:
    #         value: SS_
    #         includeRootOperations: true
    #         ignore:
    #           - syncStatus
    #           - syncStatuses
    #           - Fighter
    #           - _SubgraphErrorPolicy_
        - typeMerging:
            queryFields:
              - queryFieldName: fighter
                keyField: id
                keyArg: id


additionalResolvers:
  - ./resolvers/syncStatus.js

# additionalResolvers:
#   - targetTypeName: Query
#     targetFieldName: listQuestionsFromStackOverflow
#     sourceName: StackExchange # Which source does the target field belong to?
#     sourceTypeName: Query # Which root type does the target field belong to?
#     sourceFieldName: listQuestions # What is the source field name?
#     sourceArgs: # What args does this need to take?
#       pagesize: "{args.first}"
#     result: items # We want to extract `items` from the result and return only this one



documents:
  - ./operations/**/*.graphql

serve:
  browser: true
  playground: true
  customServerHandler: ./server.js