sources:
  - name: OwnershipService
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sbauch/nfight-ownership
  - name: GameDataService
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sbauch/nfight-gamedata
    transforms:
      - rename:
          renames:
            - from:
                type: Query
                field: nftprojects
              to:
                type: Query
                field: projects

additionalTypeDefs: |
  extend type Fighter {
    skills: FighterSkill @resolveTo(
      sourceName: "GameDataService",
      sourceTypeName: "Query",
      sourceFieldName: "fighterSkills",
      keyField: "id",
      keysArg: "where.id_in"
    )
  }

documents:
  - ./operations/**/*.graphql

serve:
  browser: true
  # playground: true
  cors:
    origin: '*'
  # customServerHandler: ./server.js

