sources:
  - name: ownership
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sbauch/nfight-ownership
      batch: true
    transforms:
      - typeMerging:
          queryFields:
            # With batching
            - queryFieldName: fighters
              keyField: id
              keyArg: 'where.id_in'
  - name: savestate
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sbauch/nfight-gamedata
      batch: false
    transforms:
      - prefix:
          value: SS_
          includeRootOperations: true
          ignore:
            - Fighter
            - Bytes
            - _SubgraphErrorPolicy_
      - typeMerging:
          queryFields:
            - queryFieldName: SS_fighter
              keyField: id
              keyArg: id
      - rename:
          mode: wrap
          renames:
            - from:
                type: Query
                field: SS_nftprojects
              to:
                type: Query
                field: projects
additionalResolvers:
  - ./resolvers/fighters.js
documents:
  - ./operations/**/*.graphql

serve:
  browser: true
  playground: true
  port: 4001
  cors:
    origin: '*'
  # customServerHandler: ./server.js

