sources:
  - name: savestate
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sbauch/nfight-gamedata
      batch: true
    transforms:
      - typeMerging:
          queryFields:
            # With batching
            - queryFieldName: fighters
              keyField: id
              keyArg: 'where.id_in'
            - queryFieldName: syncStatuses
              keyField: id
              keyArg: 'where.id_in'
  - name: ownership
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sbauch/nfight-ownership
      batch: true
    transforms:
      - prefix:
          value: L1_
          includeRootOperations: true
          ignore:
            - syncStatus
            - syncStatuses
            - Fighter
            - _SubgraphErrorPolicy_
      - typeMerging:
          queryFields:
            - queryFieldName: L1_fighter
              keyField: id
              keyArg: id
            - queryFieldName: L1_syncStatuses
              keyField: id
              keyArg: id

additionalTypeDefs: |
  extend type Fighter {
    syncStatus: SyncStatus!
    syncStatusString: String!
  }
additionalResolvers:
  - ./resolvers/syncStatus.js

documents:
  - ./operations/getFighter.query.graphql

serve:
  browser: true
  playground: true
  # customServerHandler: ./server.js