sources:
  - name: ownership
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sbauch/nfight-ownership
      batch: true
    transforms:
      - typeMerging:
          queryFields:
            # With batching
            - queryFieldName: fighters
              keyField: id
              keyArg: 'where.id_in'
            - queryFieldName: syncStatuses
              keyField: id
              keyArg: 'where.id_in'

  - name: savestate
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sbauch/nfight-gamedata
      batch: false
    transforms:
      - typeMerging:
          queryFields:
            - queryFieldName: fighter
              keyField: id
              keyArg: id
            - queryFieldName: syncStatus
              keyField: id
              keyArg: id

additionalTypeDefs: |
  extend type Fighter {
    syncStatus: SyncStatus!
    syncStatusString: String!
  }

additionalResolvers:
  - ./resolvers/syncStatus.js


documents:
  - ./operations/**/*.graphql

serve:
  browser: true
  playground: true
  # customServerHandler: ./server.js