sources:
  - name: savestate
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sbauch/nfight-gamedata
      batch: true
    transforms:
      - rename:
          mode: wrap
          renames:
            - from:
                type: Query
                field: nftprojects
              to:
                type: Query
                field: projects
      - typeMerging:
          queryFields:
            # With batching
            - queryFieldName: fighters
              keyField: id
              keyArg: 'where.id_in'
            - queryFieldName: syncStatuses
              keyField: fighter
              keyArg: fighter
  - name: ownership
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sbauch/nfight-ownership
      batch: true
    transforms:
      - prefix:
          value: L1_
          includeRootOperations: false
          includeTypes: false
          ignore:
            - syncStatus
            - syncStatuses
            - Fighter
            - _SubgraphErrorPolicy_
            - Bytes
      - typeMerging:
          queryFields:
            - queryFieldName: fighter
              keyField: id
              keyArg: id
            - queryFieldName: syncStatus
              keyField: fighter
              keyArg: fighter

additionalTypeDefs: |
  extend type Fighter {
    syncStatus: SyncStatus!
    syncStatusString: String!
  }
additionalResolvers:
  - ./resolvers/syncStatus.js

documents:
  - ./operations/**.*.graphql

serve:
  browser: true
  playground: true
  # customServerHandler: ./server.js